<a href="https://colab.research.google.com/github/gomlfx/CodeSearchNet/blob/master/LS_DS_113_Join_and_Reshape_Data_Assignment_Mike_Smith.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lambda School Data Science

*Unit 1, Sprint 1, Module 3*

---

# Join and Reshape datasets

Objectives
- concatenate data with pandas
- merge data with pandas
-  understand tidy data formatting
-  melt and pivot data with pandas

Links
- [Pandas Cheat Sheet](https://github.com/pandas-dev/pandas/blob/master/doc/cheatsheet/Pandas_Cheat_Sheet.pdf)
- [Tidy Data](https://en.wikipedia.org/wiki/Tidy_data)
  - Combine Data Sets: Standard Joins
  - Tidy Data
  - Reshaping Data
- Python Data Science Handbook
  - [Chapter 3.6](https://jakevdp.github.io/PythonDataScienceHandbook/03.06-concat-and-append.html), Combining Datasets: Concat and Append
  - [Chapter 3.7](https://jakevdp.github.io/PythonDataScienceHandbook/03.07-merge-and-join.html), Combining Datasets: Merge and Join
  - [Chapter 3.8](https://jakevdp.github.io/PythonDataScienceHandbook/03.08-aggregation-and-grouping.html), Aggregation and Grouping
  - [Chapter 3.9](https://jakevdp.github.io/PythonDataScienceHandbook/03.09-pivot-tables.html), Pivot Tables
  
Reference
- Pandas Documentation: [Reshaping and Pivot Tables](https://pandas.pydata.org/pandas-docs/stable/reshaping.html)
- Modern Pandas, Part 5: [Tidy Data](https://tomaugspurger.github.io/modern-5-tidy.html)

In [11]:
!wget https://s3.amazonaws.com/instacart-datasets/instacart_online_grocery_shopping_2017_05_01.tar.gz

--2019-11-06 01:56:43--  https://s3.amazonaws.com/instacart-datasets/instacart_online_grocery_shopping_2017_05_01.tar.gz
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.165.221
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.165.221|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 205548478 (196M) [application/x-gzip]
Saving to: ‘instacart_online_grocery_shopping_2017_05_01.tar.gz’

instacart_online_gr 100%[===================>] 196.03M  47.6MB/s    in 4.5s    

2019-11-06 01:56:48 (43.3 MB/s) - ‘instacart_online_grocery_shopping_2017_05_01.tar.gz’ saved [205548478/205548478]



In [12]:
!tar --gunzip --extract --verbose --file=instacart_online_grocery_shopping_2017_05_01.tar.gz

instacart_2017_05_01/
instacart_2017_05_01/._aisles.csv
instacart_2017_05_01/aisles.csv
instacart_2017_05_01/._departments.csv
instacart_2017_05_01/departments.csv
instacart_2017_05_01/._order_products__prior.csv
instacart_2017_05_01/order_products__prior.csv
instacart_2017_05_01/._order_products__train.csv
instacart_2017_05_01/order_products__train.csv
instacart_2017_05_01/._orders.csv
instacart_2017_05_01/orders.csv
instacart_2017_05_01/._products.csv
instacart_2017_05_01/products.csv


In [13]:
%cd instacart_2017_05_01

/content/instacart_2017_05_01/instacart_2017_05_01


In [7]:
!ls -lh *.csv

-rw-r--r-- 1 502 staff 2.6K May  2  2017 aisles.csv
-rw-r--r-- 1 502 staff  270 May  2  2017 departments.csv
-rw-r--r-- 1 502 staff 551M May  2  2017 order_products__prior.csv
-rw-r--r-- 1 502 staff  24M May  2  2017 order_products__train.csv
-rw-r--r-- 1 502 staff 104M May  2  2017 orders.csv
-rw-r--r-- 1 502 staff 2.1M May  2  2017 products.csv


# Assignment

## Join Data Practice

These are the top 10 most frequently ordered products. How many times was each ordered? 

1. Banana
2. Bag of Organic Bananas
3. Organic Strawberries
4. Organic Baby Spinach 
5. Organic Hass Avocado
6. Organic Avocado
7. Large Lemon 
8. Strawberries
9. Limes 
10. Organic Whole Milk

First, write down which columns you need and which dataframes have them.

Next, merge these into a single dataframe.

Then, use pandas functions from the previous lesson to get the counts of the top 10 most frequently ordered products.

In [88]:
##### YOUR CODE HERE #####
#explore each csv  by sampling item name
import pandas as pd
pd.options.display.max_rows=999
#pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
df = pd.read_csv("aisles.csv")
print(df.shape)
print(df)



(134, 2)
     aisle_id                          aisle
0    1         prepared soups salads        
1    2         specialty cheeses            
2    3         energy granola bars          
3    4         instant foods                
4    5         marinades meat preparation   
5    6         other                        
6    7         packaged meat                
7    8         bakery desserts              
8    9         pasta sauce                  
9    10        kitchen supplies             
10   11        cold flu allergy             
11   12        fresh pasta                  
12   13        prepared meals               
13   14        tofu meat alternatives       
14   15        packaged seafood             
15   16        fresh herbs                  
16   17        baking ingredients           
17   18        bulk dried fruits vegetables 
18   19        oils vinegars                
19   20        oral hygiene                 
20   21        packaged cheese              
2

In [87]:
import pandas as pd
pd.options.display.max_rows=999
#pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
df = pd.read_csv("departments.csv")
print(df.shape)
print(df)

(21, 2)
    department_id       department
0   1              frozen         
1   2              other          
2   3              bakery         
3   4              produce        
4   5              alcohol        
5   6              international  
6   7              beverages      
7   8              pets           
8   9              dry goods pasta
9   10             bulk           
10  11             personal care  
11  12             meat seafood   
12  13             pantry         
13  14             breakfast      
14  15             canned goods   
15  16             dairy eggs     
16  17             household      
17  18             babies         
18  19             snacks         
19  20             deli           
20  21             missing        


In [86]:
import pandas as pd
pd.options.display.max_rows=999
#pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
df = pd.read_csv("order_products__prior.csv")
print(df.shape)
print(df)

(32434489, 4)
          order_id  product_id  add_to_cart_order  reordered
0         2         33120       1                  1        
1         2         28985       2                  1        
2         2         9327        3                  0        
3         2         45918       4                  1        
4         2         30035       5                  0        
...      ..           ...      ..                 ..        
32434484  3421083   39678       6                  1        
32434485  3421083   11352       7                  0        
32434486  3421083   4600        8                  0        
32434487  3421083   24852       9                  1        
32434488  3421083   5020        10                 1        

[32434489 rows x 4 columns]


In [85]:
import pandas as pd
pd.options.display.max_rows=999
#pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
df = pd.read_csv("order_products__train.csv")
print(df.shape)
print(df)

(1384617, 4)
         order_id  product_id  add_to_cart_order  reordered
0        1         49302       1                  1        
1        1         11109       2                  1        
2        1         10246       3                  0        
3        1         49683       4                  0        
4        1         43633       5                  1        
...     ..           ...      ..                 ..        
1384612  3421063   14233       3                  1        
1384613  3421063   35548       4                  1        
1384614  3421070   35951       1                  1        
1384615  3421070   16953       2                  1        
1384616  3421070   4724        3                  1        

[1384617 rows x 4 columns]


In [84]:
import pandas as pd
pd.options.display.max_rows=999
#pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
df = pd.read_csv("orders.csv")
print(df.shape)
print(df)

(3421083, 7)
         order_id  user_id eval_set  order_number  order_dow  \
0        2539329   1        prior    1             2           
1        2398795   1        prior    2             3           
2        473747    1        prior    3             3           
3        2254736   1        prior    4             4           
4        431534    1        prior    5             4           
...         ...   ..          ...   ..            ..           
3421078  2266710   206209   prior    10            5           
3421079  1854736   206209   prior    11            4           
3421080  626363    206209   prior    12            1           
3421081  2977660   206209   prior    13            1           
3421082  272231    206209   train    14            6           

         order_hour_of_day  days_since_prior_order  
0        8                 NaN                      
1        7                  15.0                    
2        12                 21.0                    
3     

In [83]:
import pandas as pd
pd.options.display.max_rows=999
#pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
df = pd.read_csv("products.csv")
print(df.shape)
print(df)


(49688, 4)
       product_id  \
0      1            
1      2            
2      3            
3      4            
4      5            
...   ..            
49683  49684        
49684  49685        
49685  49686        
49686  49687        
49687  49688        

                                                            product_name  \
0      Chocolate Sandwich Cookies                                          
1      All-Seasons Salt                                                    
2      Robust Golden Unsweetened Oolong Tea                                
3      Smart Ones Classic Favorites Mini Rigatoni With Vodka Cream Sauce   
4      Green Chile Anytime Sauce                                           
...                          ...                                           
49683  Vodka, Triple Distilled, Twist of Vanilla                           
49684  En Croute Roast Hazelnut Cranberry                                  
49685  Artisan Baguette                             

In [93]:
#departments(21 rows), aisles(134 rows), products (49688 rows) files have string data like banana, etc. 
#logically, you can see less depts vs aisles vs products, etc. So our strings are in products csv. There are 49000 product id's, which is our items?
#search products.csv file for our string matches:
#Bag of Organic Bananas
#Organic Strawberries
#Organic Baby Spinach
#Organic Hass Avocado
#Organic Avocado
#Large Lemon
#Strawberries
#Limes
#Organic Whole Milk
import numpy as np
df=pd.read_csv('products.csv')
print(np.where((df['product_name']=='Banana')))
print(np.where((df['product_name']=='Bag of Organic Bananas')))
print(np.where((df['product_name']=='Organic Strawberries')))
print(np.where((df['product_name']=='Organic Baby Spinach')))
print(np.where((df['product_name']=='Organic Hass Avocado')))
print(np.where((df['product_name']=='Large Lemon')))
print(np.where((df['product_name']=='Strawberries')))
print(np.where((df['product_name']=='Limes')))
print(np.where((df['product_name']=='Organic Whole Milk')))

(array([24851]),)
(array([13175]),)
(array([21136]),)
(array([21902]),)
(array([47208]),)
(array([47625]),)
(array([16796]),)
(array([26208]),)
(array([27844]),)


In [94]:
#Index of items found, print row to confirm our item
print(df.iloc[[24851]])
print(df.iloc[[13175]])
print(df.iloc[[21136]])
print(df.iloc[[21902]])
print(df.iloc[[47208]])
print(df.iloc[[47625]])
print(df.iloc[[16796]])
print(df.iloc[[26208]])
print(df.iloc[[27844]])

       product_id product_name  aisle_id  department_id
24851  24852       Banana       24        4            
       product_id            product_name  aisle_id  department_id
13175  13176       Bag of Organic Bananas  24        4            
       product_id          product_name  aisle_id  department_id
21136  21137       Organic Strawberries  24        4            
       product_id          product_name  aisle_id  department_id
21902  21903       Organic Baby Spinach  123       4            
       product_id          product_name  aisle_id  department_id
47208  47209       Organic Hass Avocado  24        4            
       product_id product_name  aisle_id  department_id
47625  47626       Large Lemon  24        4            
       product_id  product_name  aisle_id  department_id
16796  16797       Strawberries  24        4            
       product_id product_name  aisle_id  department_id
26208  26209       Limes        24        4            
       product_id        p

In [122]:
#now use product_id to find how many times was each ordered.
df=pd.read_csv('products.csv')
df_result = df('Banana').count()
print(df_result)

TypeError: ignored

## Reshape Data Section

- Replicate the lesson code
- Complete the code cells we skipped near the beginning of the notebook
- Table 2 --> Tidy
- Tidy --> Table 2
- Load seaborn's `flights` dataset by running the cell below. Then create a pivot table showing the number of passengers by month and year. Use year for the index and month for the columns. You've done it right if you get 112 passengers for January 1949 and 432 passengers for December 1960.

In [6]:
flights = sns.load_dataset('flights')

NameError: ignored

In [0]:
##### YOUR CODE HERE #####

## Join Data Stretch Challenge

The [Instacart blog post](https://tech.instacart.com/3-million-instacart-orders-open-sourced-d40d29ead6f2) has a visualization of "**Popular products** purchased earliest in the day (green) and latest in the day (red)." 

The post says,

> "We can also see the time of day that users purchase specific products.

> Healthier snacks and staples tend to be purchased earlier in the day, whereas ice cream (especially Half Baked and The Tonight Dough) are far more popular when customers are ordering in the evening.

> **In fact, of the top 25 latest ordered products, the first 24 are ice cream! The last one, of course, is a frozen pizza.**"

Your challenge is to reproduce the list of the top 25 latest ordered popular products.

We'll define "popular products" as products with more than 2,900 orders.



In [0]:
##### YOUR CODE HERE #####

## Reshape Data Stretch Challenge

_Try whatever sounds most interesting to you!_

- Replicate more of Instacart's visualization showing "Hour of Day Ordered" vs "Percent of Orders by Product"
- Replicate parts of the other visualization from [Instacart's blog post](https://tech.instacart.com/3-million-instacart-orders-open-sourced-d40d29ead6f2), showing "Number of Purchases" vs "Percent Reorder Purchases"
- Get the most recent order for each user in Instacart's dataset. This is a useful baseline when [predicting a user's next order](https://www.kaggle.com/c/instacart-market-basket-analysis)
- Replicate parts of the blog post linked at the top of this notebook: [Modern Pandas, Part 5: Tidy Data](https://tomaugspurger.github.io/modern-5-tidy.html)

In [0]:
##### YOUR CODE HERE #####